### ISSUE TITLE
can't preview the pipeline 

### ISSUE THREAD

**Issue by AngelAlvarado** [streamsets/datacollector-docker#2]
Hi,

I'm trying this docker container, so far I am able to create the pipeline but when trying to preview it I get this error:

>  java.lang.RuntimeException: java.io.FileNotFoundException: /etc/sdc/email-password.txt (Permission denied) 

Can you help me out? 

I should mention that I ran the container using the following command:

> $ docker run -p 18630:18630  -u $(id -u):$(id -g) -v $PWC:/data:rw  streamsets/datacollector dc

**-u $(id -u)...** because this docker issue: https://github.com/docker/docker/issues/3206

**Comment by eosrei** [comment]
Starting docker with `-u` means the user isn't root, therefore you don't have access to modify/create files in  `/etc`.

**Comment by kunickiaj** [comment]
This image actually runs as user "sdc" by default.

You'll want to modify the `Dockerfile` and build your own image if you want to change the ownership of SDC installed files.

If you're simply looking to persist your SDC_DATA directory I'd recommend using a data-only container as outlined in the README file.
