### ISSUE TITLE
start fail because ulimit

### ISSUE THREAD

**Issue by songjiyang** [streamsets/datacollector-docker#21]
when i run `docker run --restart on-failure -p 18630:18630 -d --name streamsets-dc streamsets/datacollector dc`, it restart endlessly

docker logs output is
```
Java 1.8 detected; adding $SDC_JAVA8_OPTS of "-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -Djdk.nio.maxCachedBufferSize=262144" to $SDC_JAVA_OPTS
Configuration of maximum open file limit is too low: 1024 (expected at least 32768). Please consult https://goo.gl/6dmjXd
```

i fix it use
`docker run --ulimit nofile=65536 --restart on-failure -p 18630:18630 -d --name streamsets-dc streamsets/datacollector dc`

**Comment by dimaspivak** [comment]
This sounds like expected behavior.
