### ISSUE TITLE
How to run this docker image for other SDC_HOME

### ISSUE THREAD

**Issue by manas86** [streamsets/datacollector-docker#23]
As subject line specified, how can I override current/existing Environment/arguments to user-defined.  

e.g. I would like my configuration to be set as follow in my child dockerfile instead of existing one. 
```
ARG SDC_HOME="/app/streamsets/treamsets-datacollector"
ENV SDC_CONF=${SDC_HOME}/etc \
    SDC_DATA={SDC_HOME}/data \
    SDC_DIST=${SDC_HOME} \
    SDC_HOME=${SDC_HOME} \
    SDC_LOG=${SDC_HOME}/logs \
    SDC_RESOURCES=${SDC_HOME}/resources \
    USER_LIBRARIES_DIR=${SDC_HOME}/streamsets-datacollector-user-libs
ENV STREAMSETS_LIBRARIES_EXTRA_DIR="${SDC_DIST}/streamsets-libs-extras"
```
can you suggest some sample where we can have streamsets dc running on it';s own path?

**Comment by jeff303** [comment]
We don't use Github issues.  Please engage on one of our [existing community venues](https://streamsets.com/community/).

**Comment by manas86** [comment]
thanks will do likewise. appreciated.
