### ISSUE TITLE
sha1sum: unrecognized option: status

### ISSUE THREAD

**Issue by mandrews** [streamsets/datacollector-docker#5]
I updated my Dockerfile to use the `2.1.0.0` tag. It's working great, but I ran into an issue when using `streamsets stagelibs` install some individual stages (I needed to do this since the [Dockerfile has been updated to install core tarball instead of all](https://github.com/streamsets/datacollector-docker/commit/c82a2a3))

```
FROM streamsets/datacollector:2.1.0.0
RUN  /opt/streamsets-datacollector-2.1.0.0/bin/streamsets stagelibs -install=$STAGELIBS
```

```
sha1sum: unrecognized option: status
BusyBox v1.24.2 (2016-05-31 09:35:34 GMT) multi-call binary.

Usage: sha1sum [-c[sw]] [FILE]...

Print or check SHA1 checksums

        -c      Check sums against list in FILEs
        -s      Don't output anything, status code shows success
        -w      Warn about improperly formatted checksum lines
Failed! running sha1sum --status -c stage-lib-manifest.properties.sha1 in /tmp/sdc-setup-5
```

I was able to work around this by editing the file to replace the `--status` flag with `-s`:

```
RUN   sed -i -e 's/run sha1sum --status/run sha1sum -s/g'  /opt/streamsets-datacollector-2.1.0.0/libexec/_stagelibs
```

[Related JIRA](https://issues.streamsets.com/browse/SDC-4075)

**Comment by jloveland** [comment]
+1

**Comment by kunickiaj** [comment]
Fixed, new images available on docker hub.
