### ISSUE TITLE
Missing nightly build version streamsets-datacollector-core-2.5.0.0-SNAPSHOT.tgz

### ISSUE THREAD

**Issue by cscetbon** [streamsets/datacollector-docker#9]
Hey, 

We can't build the latest docker version because the file is missing :
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>datacollector/l
atest/tarball/streamsets-datacollector-core-2.5.0.0-SNAPSHOT.tgz</Key><RequestId>99827EE9AF2ADF61</Re
questId><HostId>R2sjrPDHBROCR8A5EJg5rX4qzBdgXEuOeStkXysbFxqv0IRlT/k1Xhd2Qqs8510Bk09Vg7rdi3c=</HostId>
</Error>
```

**Comment by dimaspivak** [comment]
Hi @cscetbon,

We push nightly images automatically to Docker Hub every time one of our builds completes: https://hub.docker.com/r/streamsets/datacollector/tags/. If you'd like to do the build yourself, you'd need to supply the `SDC_URL` and `SDC_VERSION` build-args when running the build.

**Comment by cscetbon** [comment]
@dimaspivak yeah that's what I'm seeing in your dockerfile. Then it should certainly be specified in the README.md in the `Deriving a new image` section.

Thanks

**Comment by dimaspivak** [comment]
@cscetbon You shouldn't need to pass the build arg if building a derived image. In that case, simply pass the desired image that we've pushed to Docker Hub as the `FROM` in your Dockerfile.

**Comment by cscetbon** [comment]
okay in that case you're totally right ;)
